export const GET_CROP_LIST = 'GET_CROP_LIST';
export type GET_CROP_LIST = typeof GET_CROP_LIST;

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export type SET_CURRENT_USER = typeof SET_CURRENT_USER;

export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export type GET_CURRENT_USER = typeof GET_CURRENT_USER;

export const REMOVE_CURRENT_USER = 'REMOVE_CURRENT_USER';
export type REMOVE_CURRENT_USER = typeof REMOVE_CURRENT_USER;

export const REGISTER_USER = 'REGISTER_USER';
export type REGISTER_USER = typeof REGISTER_USER;